# Generated by Django 4.0.4 on 2022-08-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_firstname_orders_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
